# Thanks to Mkyong for mysql and hikari settings
# http://www.mkyong.com/spring-boot/spring-boot-jdbc-mysql-hikaricp-example/

#disbale Spring banner
# By quoting the value, you disable yaml's automatic-cast-to-boolean feature.
# https://github.com/spring-projects/spring-boot/issues/4600#issuecomment-219687848
spring:
  main:
    banner-mode: 'OFF'

  # local MongoDB:
  data:
    mongodb:
      uri: mongodb://localhost:27017/user_db

  #logging
logging:
  level:
    org:
      springframework:
        data: debug
