DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID INT PRIMARY KEY, NAME VARCHAR(255), DESCRIPTION TEXT);

DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(
  ID INT PRIMARY KEY,
  NAME VARCHAR(255)
);

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK (
  ID INT PRIMARY KEY,
  NAME VARCHAR(255),
  DESCRIPTION TEXT
);

DROP TABLE IF EXISTS BOOK_AUTHOR;
CREATE TABLE `BOOK_AUTHOR` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `BOOK_ID` INT(11) NULL DEFAULT NULL,
  `AUTHOR_ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_book_author_book` (`BOOK_ID`),
  INDEX `FK_book_author_author` (`GENRE_ID`),
  CONSTRAINT `FK_book_genre_book` FOREIGN KEY (`BOOK_ID`) REFERENCES `book` (`ID`),
  CONSTRAINT `FK_book_genre_genre` FOREIGN KEY (`AUTHOR_ID`) REFERENCES `author` (`ID`)
);

DROP TABLE IF EXISTS BOOK_GENRE;
CREATE TABLE `BOOK_GENRE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `BOOK_ID` INT(11) NULL DEFAULT NULL,
  `GENRE_ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_book_genre_book` (`BOOK_ID`),
  INDEX `FK_book_genre_genre` (`GENRE_ID`),
  CONSTRAINT `FK_book_genre_book` FOREIGN KEY (`BOOK_ID`) REFERENCES `book` (`ID`),
  CONSTRAINT `FK_book_genre_genre` FOREIGN KEY (`GENRE_ID`) REFERENCES `genre` (`ID`)
);



