DROP TABLE IF EXISTS BOOK_AUTHOR;
DROP TABLE IF EXISTS BOOK_GENRE;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS AUTHOR;

CREATE TABLE GENRE(ID INT PRIMARY KEY, NAME VARCHAR(255), DESCRIPTION TEXT);

CREATE TABLE AUTHOR(
  ID INT PRIMARY KEY,
  NAME VARCHAR(255)
);

CREATE TABLE BOOK (
  ID INT PRIMARY KEY,
  NAME VARCHAR(255),
  DESCRIPTION TEXT
);

CREATE TABLE `BOOK_AUTHOR` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `BOOK_ID` INT(11) NULL DEFAULT NULL,
  `AUTHOR_ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_book_author_book` (`BOOK_ID`),
  INDEX `FK_book_author_author` (`AUTHOR_ID`),
  CONSTRAINT `FK_book_author_book` FOREIGN KEY (`BOOK_ID`) REFERENCES `BOOK` (`ID`),
  CONSTRAINT `FK_book_author_author` FOREIGN KEY (`AUTHOR_ID`) REFERENCES `AUTHOR` (`ID`)
);

CREATE TABLE `BOOK_GENRE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `BOOK_ID` INT(11) NULL DEFAULT NULL,
  `GENRE_ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_book_genre_book` (`BOOK_ID`),
  INDEX `FK_book_genre_genre` (`GENRE_ID`),
  CONSTRAINT `FK_book_genre_book` FOREIGN KEY (`BOOK_ID`) REFERENCES `BOOK` (`ID`),
  CONSTRAINT `FK_book_genre_genre` FOREIGN KEY (`GENRE_ID`) REFERENCES `GENRE` (`ID`)
);



